name: Upload Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: macos-11

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: yarn install 
        run: |
          yarn
          yarn global add xvfb-maybe 

      - name: Build application
        run: |
          yarn build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Upload build folder to S3
        run: |
          aws s3 sync ./dist_electron s3://s3-desktop-app
