name: Upload Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: macos-11

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: yarn install
        run: |
          yarn
          yarn global add xvfb-maybe

      - name: Build application && release app
        run: |
          yarn release
          yarn upload-dist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PICGO_ENV_S3_SECRET_ID: ${{ secrets.PICGO_ENV_S3_SECRET_ID }}
          PICGO_ENV_S3_SECRET_KEY: ${{ secrets.PICGO_ENV_S3_SECRET_KEY }}
          PICGO_ENV_S3_ACCOUNT_ID: ${{ secrets.PICGO_ENV_S3_ACCOUNT_ID }}


